version: "1"

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      CONNECTION_STRING: mongodb://mongo_db:27017/share2teach
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
