version: "3"

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 1122:1122
    environment:
      PORT: 1122
      CONNECTION_STRING: mongodb://mongo_db:27017/share2teach
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
