export const userList = [
  {
    id: 1,
    fName: "Travis",
    lName: "Scott",
    email: "jack@cactus.com",
    password: "laFlam3",
    cPassword: "laFlam3",
    affiliation: "null",
    credentials: "null",
    role: "educator",
  },
  {
    id: 2,
    fName: "Aubrey",
    lName: "Grayham",
    email: "drizzy@ovo.com",
    password: "the6god",
    cPassword: "the6god",
    affiliation: "null",
    credentials: "null",
    role: "educator",
  },
  {
    id: 3,
    fName: "shaun",
    lName: "carters",
    email: "jayz@defjam.com",
    password: "h0v",
    cPassword: "h0v",
    affiliation: "null",
    credentials: "null",
    role: "admin",
  },
  {
    id: 4,
    fName: "Kanye",
    lName: "West",
    email: "yeezy@goodmusic.com",
    password: "y3",
    cPassword: "y3",
    affiliation: "null",
    credentials: "null",
    role: "moderator",
  },
];
